config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  resources :comments, only: [:create]
  devise_for :user
  match '/likes/create_like/:id/:type/:method' => 'likes#create', via: :put, :as => :create_like
  
  namespace :api do
    namespace :v1, format: :json do
      resources :posts
      devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout',sign_up: 'sing_up'}
    end
  end  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  
  has_attached_file :image, :styles => { :small => "70x70>" },
                  :url  => "/assets/posts/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/posts/:id/:style/:basename.:extension", 
                  presence_post: true

  # validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 3.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  
  
  
  
  validates :title, presence: true
  # validates :img_url, presence_post: true
  validates :body_text, presence_post: true  
  validates :link_url, presence_post: true, http_url: true
  
  paginates_per(30)
    # повертає відповідну сторінку до переданого номера сторінки
    # якщо параметр nill то повертає першу сторінку
  scope :posts_per_page, ->(page) {
    page = 1 if page.to_i.nil?
    # paginates_per(10)
    order(id: :desc).page page
  }
    # Перевірка на вмісткість посилання в бд
    # Якщо існує то відміняємо зберігання та вивидимо помилку 
    # якщо не існує то зберігаємо
  def exists_posts
    if Post.exists?(link_url: self[:link_url])
      errors.add(:link_url, "already exists!")
      throw :abort
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::BaseApiController
  before_action :set_post, only: [ :show ] #, :edit, :update, :destroy]
  before_action :authenticate_user_with_token!, only: [:create]
  
  def index
    @posts = Post.posts_per_page(params[:page])
    if @posts.exists?
      render json: { :posts => @posts}, status: 200
    else
      render json: @posts.errors, status: :unprocessable_entity
    end
  end
  
  def show
    if @posts.present?
      # @link = @link.to_hash
      render json: @posts, include: ['comments'], status: 200
    else
      render json: { :error => "page not found" }, status: 404
    end
  end
  
  def create
    
    # @posts = current_user.posts.new(posts_params)
    # if @posts.save
    #   render json: @posts, status: 201 
    # else
    #   render json: @posts.errors, status: :unprocessable_entity
    # end
  end
  
   private
    def set_post
      @posts = Post.find_by(id: params[:id])
    end
    # def link_params
    #   params.require(:link).permit(:title, :url)
    # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :checking_of_equality, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]
  
  def index
    @post = Post.order(id: :desc).page params[:page]
  end

  def show
    if user_signed_in?
      @comment = current_user.comments.new
    end
    @comments = @post.comments.order(id: :DESC)
  end

  def new
    @post = current_user.posts.new
    @post.post_type = params[:post_type]
    set_visitor_sessions params[:post_type]
  end

  def edit
    if @post.post_type == nil or @post.post_type == ""
      redirect_to root_path, notice: 'Something went wrong! You can not edit this news right now. Try later.'
    end
    set_visitor_sessions @post.post_type
  end

  def create
    @post = current_user.posts.new(post_params)
    # byebug
    if @post.save
      redirect_to posts_url, notice: 'Link was successfully created.'
    else
      set_visitor_sessions params[:post][:post_type]
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Link was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy 
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end
  
  private
    def set_visitor_sessions param
      session[:post_type] = param
    end
    def set_post
      @post = Post.find_by(id: params[:id]) or render(:not_found, status: 404)
    end
    def post_params
      case params[:post][:post_type]
      when "Link"
        return params.require(:post).permit(:title, :post_type, :link_url, :user_id)
      when "Image"
        return params.require(:post).permit(:title, :post_type, :image, :user_id)
      when "Text"
        return params.require(:post).permit(:title, :post_type, :body_text, :user_id)
      else
        logger.debug "You gave me #{params[:post][:post_type]} -- I have no idea what to do with that."
        params[:post][:post_type] = nil
      end
    end
    def checking_of_equality
      redirect_back(fallback_location: root_path, notice: 'You are not the creator of this news!') unless @post.user == current_user
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_form.html.erb
<%= render 'layouts/error', obj: @post%>
<%= render(:partial => 'posts/form/location', :handlers => [:erb], :formats => [:js], session: session)%>

<% if @post.post_type == "Link" || @post.post_type == "Image" || @post.post_type == "Text" %>
  <%= form_for @post, :html => { :multipart => true} do |f| %>
    <div class="form-group row">
      <%= f.label :title, :class => "col-2 col-form-label"%>
      <div class="col-10">
        <%= f.text_field :title, :class =>"form-control"%>
      </div>
    </div>
    
    <%= render "posts/form/f#{@post.post_type.downcase}", f: f%>
    
    <div class="form-group row">
      <div class="col-12">
        <%= f.button :submit, class: "btn btn-primary float-right" do %>
          POST IT
        <% end %>
      </div>
    </div>
    
    <%= f.hidden_field :post_type, value: @post.post_type %>
  
  <% end%>
<% else %>
  <%= redirect_to root_path %>
<% end %>

app/views/posts/_post.html.haml
%div{:class => "row link"}
  %div{:class => "like-area w-10"}
    %div{:class => "like upvote"}
      =link_to create_like_path(post.id, "Post", :upvote), method: :put, :remote => true do
        %span(class="octicon octicon-chevron-up")
    %div{:class => "like like_count_#{post.id}"}
      =all_like post.likes
    %div{:class => "like"}
      =link_to create_like_path(post.id,"Post",:downvote), method: :put, :remote => true do
        %span(class="octicon octicon-chevron-down")
  %div{:class => "link-content w-100"}
    -if post.post_type == "Link"
      %div{:class => "og-image"}
        =image_tag("default_link.gif", size: "70x70", alt: "Empty Image Link")
    -if post.post_type == "Text"
      %div{:class => "og-image"}
        =image_tag("default_text.png", size: "70x70", alt: "Empty Image Link")
    -if post.post_type == "Image"
      %div{:class => "og-image"}
        =image_tag(post.image(:small), size: "70x70", alt: post.title)
    %h4{:class => "font-weight-normal title"} 
      =link_to post.title, post
    = render "support_area", :post => post
    %div{:class => "created-at text-muted"}
      %small{:class=> "author"} 
      Submitted
      = time_ago(post.created_at) 
      by 
      = post.user.email

app/views/posts/_support_area.html.haml
%div{:class => "sup"}
  %div{:class => "comment-info"}
    %div{:class => "links-group d-inline"}
      -count_comments = (post.comments.count == 0 ? 0 : post.comments.count)
      = link_to post_path(post, anchor: "comments"), {class: "pr-2"} do
        %span(class="octicon octicon-comment")
        =count_comments
        comments 
    -if post.user == current_user 
      = link_to edit_post_path(post), {class: "pr-2"} do
        %span(class="octicon octicon-pencil")
        edit
      = link_to post, method: :delete, data: { confirm: 'Are you sure?' } do
        %span(class="octicon octicon-trashcan")
        delete

app/views/posts/edit.html.erb
<h2 class="display-3 text-center">Edit <%= @post.post_type ||= session[:post_type] unless session[:post_type] == nil %></h2>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-md-9 m-auto">
  <div id="links">
    <%= render @post  %>
  </div>
</div>


<div class="row justify-content-md-center">
  <div id="paginator">
    <%= paginate @post  %>
  </div>
</div>

app/views/posts/index.js.erb
$('#links').html('<%= escape_javascript render(@links) %>');
$('#paginator').html('<%= escape_javascript(paginate(@links, :remote => true).to_s) %>');
var page = <%= params[:page] != nil ? params[:page] : 1 %>;
history.pushState({page: page}, `Links ${page}`, `?page=${page}`);

app/views/posts/new.html.erb
<h2 class="display-3 text-center">New <%= @post.post_type ||= session[:post_type] unless session[:post_type] == nil %></h2>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="card">
  <div class="card-block">
    <h4 class="card-title">
      <a href="<%= @post.link_url %>">
        <%= @post.title%>
      </a>
    </h4>
    <h6 class="card-subtitle mb-2 text-muted">Submited <%= time_ago(@post.created_at)%> by <%= @post.user.email%></h6>
    <a href="<%= @post.link_url %>">Visit link</a>
  </div>
</div>
<hr>
<%-if user_signed_in?%>
  <%= render 'comments/new' %>
<%-end%>

<%= render 'comments/show', comments: @comments %>